[package]
name = "bright"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
delegate = "0.13.3"
derive_more = { version = "2.0.1", features = ["display"] }
dirs = "6.0.0"
humantime = "2.2.0"
thiserror = "2.0.12"
